[tool.poetry]
name = "flaskserver"
version = "0.1.0"
description = ""
authors = ["Tu Nombre <tuemail@dominio.com>"]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.2.3"
gunicorn = "^20.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
