services:
  - type: web
    name: flask-app
    env: python
    buildCommand: |
      curl -sSL https://install.python-poetry.org | python3 -
      export PATH="$HOME/.local/bin:$PATH"
      poetry install
    startCommand: |
      export PATH="$HOME/.local/bin:$PATH"
      poetry run gunicorn app:app
    envVars:
      - key: ENV
        value: production
